import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';

import path from 'path';
import { app } from 'electron';
import * as schema from './schema';

const dbPath = app.isPackaged
  ? path.join(app.getPath('userData'), 'rental.db')
  : path.join(app.getAppPath(), 'rental.db');

const sqlite = new Database(dbPath);
export const db = drizzle(sqlite, { schema });

// Helper to initialize DB (run migrations if we had them, or just sync schema)
// For this MVP without migration files, we might need to use `push` or manual table creation if Drizzle doesn't auto-create.
// However, Drizzle usually requires migration files generated by `drizzle-kit`.
// For simplicity in this "no-server" setup, we can use a helper to create tables if they don't exist
// or we can just assume `drizzle-kit push` style behavior if we set it up.
// BUT, `drizzle-kit` is a dev dependency.
// Let's write a simple "ensure tables exist" function using raw SQL for the MVP to avoid complex migration setup in Electron.

export function initDB() {
  // Items
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS items (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      sku TEXT NOT NULL UNIQUE,
      description TEXT,
      daily_rate INTEGER NOT NULL,
      deposit_amount INTEGER,
      is_active INTEGER NOT NULL DEFAULT 1,
      stock INTEGER NOT NULL DEFAULT 0,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL
    );
  `);

  // Migration: Add stock column if it doesn't exist
  try {
    sqlite.exec(`ALTER TABLE items ADD COLUMN stock INTEGER NOT NULL DEFAULT 0`);
  } catch (error) {
    // Ignore error if column already exists
  }

  // Rentals
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS rentals (
      id TEXT PRIMARY KEY,
      renter_name TEXT NOT NULL,
      renter_phone TEXT,
      renter_email TEXT,
      rent_date INTEGER NOT NULL,
      expected_return_date INTEGER,
      actual_return_date INTEGER,
      total_price_agreed INTEGER NOT NULL,
      currency TEXT NOT NULL DEFAULT 'USD',
      status TEXT NOT NULL DEFAULT 'ongoing',
      notes TEXT,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL
    );
  `);

  // Rental Items
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS rental_items (
      id TEXT PRIMARY KEY,
      rental_id TEXT NOT NULL REFERENCES rentals(id),
      item_id TEXT NOT NULL REFERENCES items(id),
      quantity INTEGER NOT NULL,
      price_per_unit INTEGER NOT NULL,
      subtotal INTEGER NOT NULL
    );
  `);

  // Settings
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS shop_settings (
      id TEXT PRIMARY KEY DEFAULT 'singleton',
      shop_display_name TEXT NOT NULL,
      currency TEXT NOT NULL DEFAULT 'USD',
      timezone TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL
    );
  `);

  // Audit Log
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS audit_log (
      id TEXT PRIMARY KEY,
      entity TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      action TEXT NOT NULL,
      user TEXT NOT NULL DEFAULT 'admin',
      before_json TEXT,
      after_json TEXT,
      timestamp INTEGER NOT NULL
    );
  `);

  console.log('Database initialized at', dbPath);
}
